/**
 * Phase 7.A.2b win-state reachability + replay-determinism invariant
 * test.
 *
 * Per `docs/PHASES.md:520-525` (Phase 7.A.2 acceptance criterion):
 *
 *   "A scripted run on a fixed fingerprint can: buy an upgrade from a
 *    ripperdoc, descend to floor 10, and defeat the boss. Win-state
 *    transition is reachable and replayable (asserted by a new test
 *    that runs the scripted log, asserts outcome === 'won', replays
 *    the same log from genesis, asserts byte-identical final state)."
 *
 * The action log is the synthesized `SELF_TEST_WIN_LOG` (generated by
 * `tools/build-win-log.ts` and pasted as a frozen literal into
 * `src/sim/self-test-win-log.ts`). The final state hash is pinned by
 * `WIN_DIGEST` in `src/core/self-test.ts`.
 */

import { describe, expect, it } from "vitest";
import { runScripted } from "../../src/sim/harness";
import {
  SELF_TEST_WIN_INPUTS,
  SELF_TEST_WIN_LOG,
} from "../../src/sim/self-test-win-log";
import { WIN_DIGEST } from "../../src/core/self-test";
import { sha256Hex } from "../../src/core/hash";

describe("win-state reachability + replay determinism (Phase 7.A.2b)", () => {
  it("the scripted winning log reaches outcome === 'won' on floor 10", () => {
    const result = runScripted({
      inputs: SELF_TEST_WIN_INPUTS,
      actions: SELF_TEST_WIN_LOG,
    });
    expect(result.outcome).toBe("won");
    expect(result.finalState.floorN).toBe(10);
    expect(result.finalState.player.hp).toBeGreaterThan(0);
  });

  it("the boss is defeated (HP 0) when outcome === 'won'", () => {
    const result = runScripted({
      inputs: SELF_TEST_WIN_INPUTS,
      actions: SELF_TEST_WIN_LOG,
    });
    const boss = result.finalState.floorState.monsters.find(
      (m) => m.kind === "monster.boss.black-ice-v0",
    );
    expect(boss).toBeDefined();
    expect(boss!.hp).toBe(0);
  });

  it("replaying the same log twice yields byte-identical final state hash", () => {
    const a = runScripted({
      inputs: SELF_TEST_WIN_INPUTS,
      actions: SELF_TEST_WIN_LOG,
    });
    const b = runScripted({
      inputs: SELF_TEST_WIN_INPUTS,
      actions: SELF_TEST_WIN_LOG,
    });
    expect(a.outcome).toBe("won");
    expect(b.outcome).toBe("won");
    expect(sha256Hex(a.finalState.stateHash)).toBe(
      sha256Hex(b.finalState.stateHash),
    );
  });

  it("the final state hash matches the pinned WIN_DIGEST", () => {
    const result = runScripted({
      inputs: SELF_TEST_WIN_INPUTS,
      actions: SELF_TEST_WIN_LOG,
    });
    expect(sha256Hex(result.finalState.stateHash)).toBe(WIN_DIGEST);
  });

  it("any prefix of the winning log replays to a deterministic intermediate state", () => {
    // Pick three prefix points: 100 actions in (mid floor 1), the
    // mid-point of the log, and the full log minus the final attack.
    const prefixes = [
      100,
      Math.floor(SELF_TEST_WIN_LOG.length / 2),
      SELF_TEST_WIN_LOG.length - 1,
    ];
    for (const p of prefixes) {
      const a = runScripted({
        inputs: SELF_TEST_WIN_INPUTS,
        actions: SELF_TEST_WIN_LOG.slice(0, p),
      });
      const b = runScripted({
        inputs: SELF_TEST_WIN_INPUTS,
        actions: SELF_TEST_WIN_LOG.slice(0, p),
      });
      expect(sha256Hex(a.finalState.stateHash)).toBe(
        sha256Hex(b.finalState.stateHash),
      );
    }
  });

  it("the scripted log includes at least one BUY action (proves shop interaction)", () => {
    let buyCount = 0;
    for (const a of SELF_TEST_WIN_LOG) {
      if (a.type === "buy") buyCount++;
    }
    expect(buyCount).toBeGreaterThan(0);
  });

  it("the scripted log includes 9 DESCEND actions (proves floors 1..9 descent)", () => {
    let descendCount = 0;
    for (const a of SELF_TEST_WIN_LOG) {
      if (a.type === "descend") descendCount++;
    }
    expect(descendCount).toBe(9);
  });
});
