/**
 * Phase 8.A.3 build-dual script. Per
 * `artifacts/decision-memo-phase-8.md` decision 7 + 17 + addendum B4.
 *
 * Builds the production bundle TWICE with different Vite `--base`
 * paths and assembles them into a single `dist-final/` tree:
 *
 *   dist-final/
 *   ├── index.html             # latest/ entry (base = /icefall/)
 *   ├── assets/                # latest/ JS, CSS, atlas
 *   └── releases/
 *       └── <commit-12>/       # base = /icefall/releases/<commit-12>/
 *           ├── index.html
 *           └── assets/
 *
 * The `releases/<commit-12>/` subtree is the content-addressed
 * pinned release; the bare `latest/` paths get re-overwritten on
 * every deploy. The 12-character commit-short is the
 * forever-collision-resistant pin (memo addendum B4).
 *
 * `releases/index.json` is NOT generated by this script — it is
 * generated by `publish-dual.mjs` after this script completes,
 * which fetches the prior deploy's index, merges, and writes.
 *
 * Usage (invoked from `.github/workflows/deploy.yml` after `npm ci`):
 *
 *   node scripts/build-dual.mjs \
 *     --commit-short=<12-hex> \
 *     [--dist-final=dist-final]
 *
 * Each `npx vite build` invocation produces deterministic bytes (same
 * as `npm run build`); the only difference between the two calls is
 * Vite's `--base` flag, which Vite uses to rewrite asset URLs in
 * `index.html`. The compiled JS bundles are byte-identical between
 * the two builds.
 */

import { execSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";

const COMMIT_HEX_RE = /^[0-9a-f]{12}$/;

export function parseArgs(argv) {
  const args = {};
  for (const a of argv.slice(2)) {
    const m = a.match(/^--([a-z-]+)=(.+)$/);
    if (!m) {
      throw new Error(`build-dual: unrecognized argument '${a}'`);
    }
    args[m[1]] = m[2];
  }
  if (!("commit-short" in args)) {
    throw new Error("build-dual: missing --commit-short=<12-hex>");
  }
  if (!COMMIT_HEX_RE.test(args["commit-short"])) {
    throw new Error(
      `build-dual: --commit-short must match ${COMMIT_HEX_RE} (got '${args["commit-short"]}')`,
    );
  }
  if (!("dist-final" in args)) {
    args["dist-final"] = "dist-final";
  }
  return args;
}

function runVite(base, distOut) {
  console.log(`build-dual: vite build --base=${base} --outDir=${distOut}`);
  execSync(
    `npx vite build --base=${JSON.stringify(base)} --outDir=${JSON.stringify(distOut)}`,
    { stdio: "inherit" },
  );
}

export function ensureEmpty(dir) {
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
}

export function copyTree(src, dest) {
  mkdirSync(dest, { recursive: true });
  cpSync(src, dest, { recursive: true });
}

async function main() {
  const args = parseArgs(process.argv);
  const commitShort = args["commit-short"];
  const distFinal = resolve(args["dist-final"]);

  ensureEmpty(distFinal);

  // 1. Build the LATEST tree. Base = /icefall/ (the same as
  //    vite.config.ts default). Vite writes to `dist/` by default;
  //    we leave it there so playwright preview (which uses
  //    `vite preview` default outDir) can serve it for e2e tests
  //    in the same CI job.
  const latestOut = resolve("dist");
  ensureEmpty(latestOut);
  runVite("/icefall/", latestOut);
  copyTree(latestOut, distFinal);

  // 2. Build the per-release tree. Base = /icefall/releases/<commit>/.
  //    Each `vite build` invocation rewrites the index.html's
  //    asset-href values to reflect the new base path; the compiled
  //    JS bytes themselves are deterministic given the same source.
  //    Re-running vite is the simplest way to get correctly-rewritten
  //    HTML without a custom HTML transformer.
  const releaseOut = resolve(`dist-build-${commitShort}`);
  ensureEmpty(releaseOut);
  runVite(`/icefall/releases/${commitShort}/`, releaseOut);
  const releaseDest = join(distFinal, "releases", commitShort);
  copyTree(releaseOut, releaseDest);

  console.log(`build-dual: assembled ${distFinal}`);
  console.log(`build-dual:   latest/  →  ${distFinal}  (also at dist/ for e2e)`);
  console.log(`build-dual:   releases/${commitShort}/  →  ${releaseDest}`);
}

const isCli =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("build-dual.mjs");
if (isCli) {
  main().catch((e) => {
    console.error(`build-dual: ${e.message}`);
    process.exit(1);
  });
}
