/**
 * Phase 7.A.2b — emit `src/sim/self-test-win-log.ts` from `buildWinLog`.
 * Run as: `npx tsx tools/emit-win-log-module.ts > src/sim/self-test-win-log.ts`
 *
 * The output module exports `SELF_TEST_WIN_INPUTS` and
 * `SELF_TEST_WIN_LOG`. The action log is encoded as a frozen tuple
 * literal so the file is self-contained (no runtime dependency on
 * `tools/`). Pinned by `WIN_DIGEST` in `src/core/self-test.ts`.
 */

import { buildWinLog, SELF_TEST_WIN_INPUTS } from "./build-win-log";
import { runScripted } from "../src/sim/harness";
import { sha256Hex } from "../src/core/hash";

const { actions } = buildWinLog();
const result = runScripted({ inputs: SELF_TEST_WIN_INPUTS, actions });
if (result.outcome !== "won") {
  throw new Error(
    `emit-win-log-module: buildWinLog did not win for default seed; outcome=${result.outcome}`,
  );
}
const winDigest = sha256Hex(result.finalState.stateHash);

// Action.type strings used in the log.
const actionTypes = new Set(actions.map((a) => a.type));

// Compute which constant names from `params.ts` we need to import.
const typeToConst: Record<string, string> = {
  attack: "ACTION_TYPE_ATTACK",
  buy: "ACTION_TYPE_BUY",
  descend: "ACTION_TYPE_DESCEND",
  drop: "ACTION_TYPE_DROP",
  equip: "ACTION_TYPE_EQUIP",
  move: "ACTION_TYPE_MOVE",
  pickup: "ACTION_TYPE_PICKUP",
  sell: "ACTION_TYPE_SELL",
  talk: "ACTION_TYPE_TALK",
  unequip: "ACTION_TYPE_UNEQUIP",
  use: "ACTION_TYPE_USE",
  wait: "ACTION_TYPE_WAIT",
};
const dirNames = ["DIR_N", "DIR_E", "DIR_S", "DIR_W", "DIR_NE", "DIR_SE", "DIR_SW", "DIR_NW"];

const importedConsts = new Set<string>();
for (const t of actionTypes) {
  const c = typeToConst[t];
  if (c === undefined) throw new Error(`unknown action type ${t}`);
  importedConsts.add(c);
}
// Direction constants used by attack/move actions.
let needsDir = false;
const dirsUsed = new Set<number>();
for (const a of actions) {
  if (a.type === "move" || a.type === "attack") {
    if (a.dir !== undefined) {
      needsDir = true;
      dirsUsed.add(a.dir);
    }
  }
}
if (needsDir) {
  for (const d of dirsUsed) {
    importedConsts.add(dirNames[d]!);
  }
}

const sortedImports = [...importedConsts].sort();

// Emit the module.
const lines: string[] = [];
lines.push("/**");
lines.push(" * Phase 7.A.2b self-test inputs and scripted winning action log.");
lines.push(" * Pinned by the `WIN_DIGEST` golden constant in");
lines.push(" * `src/core/self-test.ts` — any change here is a `rulesetVersion`");
lines.push(" * bump.");
lines.push(" *");
lines.push(" * Generated by `tools/emit-win-log-module.ts` from");
lines.push(" * `tools/build-win-log.ts` — copy-pasted as a frozen literal so");
lines.push(" * `src/sim/**` carries no cross-layer import edge to `tools/`.");
lines.push(" * Re-emit by running:");
lines.push(" *");
lines.push(" *   npx tsx tools/emit-win-log-module.ts > src/sim/self-test-win-log.ts");
lines.push(" *");
lines.push(` * Generated for fingerprint seed: ${SELF_TEST_WIN_INPUTS.seed}.`);
lines.push(` * Action count: ${actions.length}.`);
lines.push(` * Final state digest (WIN_DIGEST): ${winDigest}.`);
lines.push(" */");
lines.push("");
lines.push('import type { Action } from "../core/encode";');
lines.push('import type { FingerprintInputs } from "../core/fingerprint";');
lines.push('import {');
for (const c of sortedImports) {
  lines.push(`  ${c},`);
}
lines.push('} from "./params";');
lines.push("");
lines.push("export const SELF_TEST_WIN_INPUTS: FingerprintInputs = Object.freeze({");
lines.push(`  commitHash: ${JSON.stringify(SELF_TEST_WIN_INPUTS.commitHash)},`);
lines.push(`  rulesetVersion: ${JSON.stringify(SELF_TEST_WIN_INPUTS.rulesetVersion)},`);
lines.push(`  seed: ${JSON.stringify(SELF_TEST_WIN_INPUTS.seed)},`);
lines.push("  modIds: Object.freeze([]) as readonly string[],");
lines.push("});");
lines.push("");
lines.push("/**");
lines.push(" * Frozen winning action log. The log was synthesized by");
lines.push(" * `tools/build-win-log.ts`'s walker against the");
lines.push(" * `SELF_TEST_WIN_INPUTS` seed. When run via `runScripted` the");
lines.push(" * final state has `outcome === \"won\"` and the state-hash");
lines.push(" * matches `WIN_DIGEST` byte-for-byte.");
lines.push(" */");
lines.push("export const SELF_TEST_WIN_LOG: readonly Action[] = Object.freeze([");
for (const a of actions) {
  const constName = typeToConst[a.type]!;
  let body = `{ type: ${constName}`;
  if ("dir" in a && a.dir !== undefined) {
    body += `, dir: ${dirNames[a.dir]!}`;
  }
  if ("target" in a && a.target !== undefined) {
    body += `, target: ${a.target}`;
  }
  if ("item" in a && a.item !== undefined) {
    body += `, item: ${JSON.stringify(a.item)}`;
  }
  body += " }";
  lines.push(`  ${body},`);
}
lines.push("]);");
lines.push("");

process.stdout.write(lines.join("\n"));
